extends: substitution
message: "Use the canonical industry term '%s' instead of '%s'."
level: warning
ignorecase: false
action:
  name: replace
swap:
  '\bBusybox\b': BusyBox
  '\bGithub Actions\b': GitHub Actions
  '\bGithub\b': GitHub
  '\bJavascript\b': JavaScript
  '\bMac ?OS\b': macOS
  '\bMysql\b': MySQL
  '\bMySql\b': MySQL
  '\bNvidia\b': NVIDIA
  '\bPowershell\b': PowerShell
  '\bPytorch\b': PyTorch
  '\bTestContainers\b': Testcontainers
